name: Check Python code in functional tests

# This workflow performs some checks on the Python client used by the Boilerplate tests
# It is there to help us maintain a level of quality in our codebase and does not have to be kept on forked
# applications.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Installing PIP dependencies
      run: |
        pip3 install pylint
        pip3 install -r tests/functional/requirements.txt
    - name: Lint Python code
      run: |
        pylint --rc tests/functional/setup.cfg tests/functional/*.py

  mypy:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Installing PIP dependencies
      run: |
        pip3 install mypy
        pip3 install -r tests/functional/requirements.txt
    - name: Mypy type checking
      run: |
        mypy --config-file tests/functional/setup.cfg --check-untyped-defs tests/functional
