name: Generate ragger snapshots

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      run_for_devices: '["nanos", "nanox", "nanosp"]'

  ragger_tests:
    name: Generate ragger snapshots
    runs-on: ubuntu-latest
    needs: build_application 
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        
    - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static tesseract-ocr libtesseract-dev
          pip install --extra-index-url https://test.pypi.org/simple/ -r tests/functional/requirements.txt

      - name: Generate snapshots
        run: |
          pytest --device nanos tests/functional/test_pubkey_cmd.py --golden_run -v
          pytest --device nanosp tests/functional/test_pubkey_cmd.py --golden_run -v
          pytest --device nanox tests/functional/test_pubkey_cmd.py --golden_run -v
      - uses: actions/upload-artifact@v3
        with:
          name: images_test_pubkey_cmd
          path: tests/functional/snapshots

 