name: Unit testing with code coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  job_unit_test:
    name: Unit test
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_unit_tests.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
